version: '3'
services:
  foundaml-servver:
    build: .
    ports:
     - "8080:8080"
    restart: always
    environment:
     - POSTGRESQL_HOST=postgres
     - POSTGRESQL_PORT=5432
     - POSTGRESQL_DATABASE=postgres
     - POSTGRESQL_USERNAME=postgres
     - POSTGRESQL_PASSWORD=postgres
  postgres:
    image: "postgres:latest"
    environment:
     - POSTGRES_PASSWORD=postgres
