version: '3'
services:
  foundaml-server:
    image:  foundaml/server:0.0.1
    ports:
     - "8080:8080"
    restart: always
    env_file:
      - .env
  postgres:
    image: "postgres:latest"
    environment:
     - POSTGRES_PASSWORD=postgres
