version: '3'
services:
  foundaml-server:
    image:  foundaml/server:0.0.1
    ports:
     - "8080:8080"
    restart: always
    environment:
     - POSTGRESQL_HOST=postgres
     - POSTGRESQL_PORT=5432
     - POSTGRESQL_DATABASE=postgres
     - POSTGRESQL_USERNAME=postgres
     - POSTGRESQL_PASSWORD=postgres
     - KINESIS_ENABLED=false
     - GCP_PUBSUB_ENABLED=false
  postgres:
    image: "postgres:latest"
    environment:
     - POSTGRES_PASSWORD=postgres
