apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundaml-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: foundaml-server
  replicas: 1
  template:
    metadata:
      labels:
        app: foundaml-server
    spec:
      volumes:
        - name: service-account-creds
          secret:
            secretName: service-account-creds
      containers:
      - name: foundaml-server 
        image: foundaml/server:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: app
        resources:
          requests:
            memory: "100Mi"
            cpu: "150m"
        env:
          - name: JAVA_OPTS
            value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
          - name: POSTGRESQL_HOST
            value: "postgres-service"
          - name: POSTGRESQL_PORT
            value: "5432"
          - name: POSTGRESQL_DATABASE
            value: "postgres"
          - name: POSTGRESQL_PASSWORD
            value: "postgres"
      # esp proxy
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=8081",
          "--backend=127.0.0.1:8080",
          "--service=foundaml-service",
          "--rollout_strategy=managed",
          "--service_account_key=/etc/nginx/creds/service-account-creds.json"
          ]
        ports:
          - containerPort: 8081
        volumeMounts:
          - mountPath: /etc/nginx/creds
            name: service-account-creds
            readOnly: true
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
      # esp proxy
---
kind: Service
apiVersion: v1
metadata:
  name: foundaml-service
spec:
  type: LoadBalancer
  selector:
    app: foundaml-server 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
    name: http

