openapi: "3.0.0"
info:
  title: FoundaMl
  description: ''
  termsOfService: ''
  contact:
    name: ''
    url: ''
    email: sauray.antoine@gmail.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 0.0.1
servers:
  - url: 'http://{platform}.www.foundaml.org'
    description: Test server
    variables:
      platform:
        default: dev
        description: this value is assigned by the service provider
      port:
        enum:
          - '80'
          - '443'
        default: '80'
      basePath:
        default: ''
paths:
  /features:
    get:
      description: ''
      responses:
        '200':
          description: ''
          content:
            application.json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FeaturesConfiguration'
    post:
      description: 'Create a new features object'
      responses:
        '201':
          description: 'Successfully created a new features object'
          content:
            application.json:
              schema:
                $ref: '#/components/schemas/FeaturesConfiguration'
  /features/{featuresId}:
    get:
      description: ''
      responses:
        '200':
          description: ''
          content:
            application.json:
              schema:
                $ref: '#/components/schemas/FeaturesConfiguration'
  /labels:
    get:
      description: ''
      responses:
        '200':
          description: ''
          content:
            application.json:
              schema:
                $ref: '#/components/schemas/LabelsConfiguration'
    post:
      description: 'Create a new labels object'
      responses:
        '201':
          description: 'Successfully created a new labels object'
          content:
            application.json:
              schema:
                $ref: '#/components/schemas/LabelsConfiguration'
  /labels/{labelsId}:
    get:
      description: ''
      responses:
        '200':
          description: ''
          content:
            application.json:
              schema:
                type: object 
                items:
                  $ref: '#/components/schemas/LabelsConfiguration'
  /projects:
    get:
      description: ''
      responses:
        '200':
          description: ''
          content:
            application.json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      description: 'Create a new project'
      responses:
        '201':
          description: 'Successfully created a new project'
          content:
            application.json:
              schema:
                $ref: '#/components/schemas/Project'
  /projects/{projectId}:
    get:
      description: ''
      responses:
        '200':
          description: ''
          content:
            application.json:
              schema:
                $ref: '#/components/schemas/Project'
  /algorithms:
    post:
      description: 'create a new algorithm'
      responses:
        '201':
          description: 'Successfully created a new algorithm'
          content:
            application.json:
              schema:
                $ref: '#/components/schemas/Algorithm'
  /predictions:
    post:
      description: 'Make a prediction on a project'
      responses:
        '200':
          description: 'The prediction is successful'
          content:
            application.json:
              schema:
                $ref: '#/components/schemas/Prediction'
components:
  schemas:
    Project:
      type: object
      required:
        - id
        - name
        - problem
        - algorithms
        - policy
        - configuration
      properties:
        id:
          type: string
        name:
          type: string
        problem:
          type: string
        algorithms:
          type: array
          items:
            $ref: "#/components/schemas/Algorithm"
    Algorithm:
      type: object
      required:
        - id
        - projectId
        - backend
        - security
      properties:
        id:
          type: string
        projectId:
          type: string
        backend:
          $ref: "#/components/schemas/Backend"
        security:
          $ref: "#/components/schemas/SecurityConfiguration"
    SecurityConfiguration:
      type: object
      required:
        - encryption
        - headers
      properties:
        encryption:
          type: string
        headers:
          type: array
          items:
            type: object
            required:
              - key
              - value
            properties:
              key:
                type: string
              value:
                type: string
    Backend:
      type: object
      required:
        - class
        - host
        - port
        - featuresTransformer
        - labelsTransformer
      properties:
        class:
          type: string
        host:
          type: string
        port:
          type: integer
        featuresTransformer:
          $ref: "#/components/schemas/TensorFlowFeaturesTransformer"
        labelsTransformer:
          $ref: "#/components/schemas/TensorFlowLabelsTransformer"
    TensorFlowFeaturesTransformer:
      type: object
      required:
        - signatureName
        - fields
      properties:
        signatureName:
          type: string
        fields:
          type: array
          items:
            type: string
    TensorFlowLabelsTransformer:
      type: object
      required:
        - fields
      properties:
        fields:
          type: array
          items:
            type: object
            required:
              - from
              - to
            properties:
              from:
                type: string
              to:
                type: string
    FeaturesConfiguration:
      type: object
      required:
        - id
        - data
      properties:
        id:
          type: string
        data:
          type: array
          items:
            type: object
            required:
              - name
              - type
              - description
            properties:
              name:
                type: string
              type:
                type: string
              description:
                type: string
    LabelsConfiguration:
      type: object
      required:
        - id
        - data
      properties:
        id:
          type: string
        data:
          type: array
          items:
            type: object
            required:
              - name
              - type
              - description
            properties:
              name:
                type: string
              type:
                type: string
              description:
                type: string
    Prediction:
      type: object
      required:
        - projectId
        - features
      properties:
        projectId:
          type: string
        features:
          type: array
          items:
            oneOf:
              - type: string
              - type: number 
